services:
  frontend:
    image: frontend
    build:
      context: ./Frontend
    ports:
      - "8080:80"
    depends_on:
      - api-server
    networks:
      - app-network
    restart: always

  api-server:
    image: backend
    build:
      context: ./Backend
    ports:
      - 3000:3000
    env_file:
      - ./Backend/.env
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:example
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
